/**
 * The store and the frame dispatcher, driven by the same Rust-generated bytes
 * the protocol test uses. Nothing here mocks a frame: if the wire format moves,
 * these tests move with it.
 */

import { beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Net } from "../src/net.js";
import { HISTORY_LEN, Store, worldSummary } from "../src/state.js";
import type { ColonyStat, Hello } from "../src/protocol.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = join(here, "../../crates/server/tests/fixtures");

function load(name: string): ArrayBuffer {
  const b = readFileSync(join(fixtures, name));
  return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer;
}

/** A Net with no socket: `dispatch` is the whole surface we want to exercise. */
function dispatcher(store: Store): Net {
  return new Net("ws://unused", store);
}

const hello = (tick: number): Hello => ({
  kind: "hello",
  width: 32,
  height: 32,
  numColonies: 2,
  pheroResLog2: 8,
  tick,
});

const colony = (id: number, over: Partial<ColonyStat> = {}): ColonyStat => ({
  id,
  population: 10,
  store: 1,
  births: 0,
  deaths: 0,
  refounds: 0,
  meanSize: 1,
  meanLineage: 1,
  deliveredTotal: 0,
  ...over,
});

describe("dispatch", () => {
  let store: Store;
  let net: Net;

  beforeEach(() => {
    store = new Store();
    net = dispatcher(store);
  });

  it("routes each fixture frame to the right slot", () => {
    net.dispatch(load("hello.bin"));
    expect(store.state.hello?.width).toBe(32);

    net.dispatch(load("ants.bin"));
    expect(store.state.ants?.count).toBeGreaterThan(0);

    net.dispatch(load("phero.bin"));
    expect(store.state.phero?.w).toBe(16);

    net.dispatch(load("stats.bin"));
    expect(store.state.stats.length).toBe(2);

    net.dispatch(load("detail.bin"));
    expect(store.state.detail?.alive).toBe(true);

    net.dispatch(load("genome.bin"));
    expect(store.state.genome?.params.length).toBe(1240);

    net.dispatch(load("config.bin"));
    expect(store.state.config.size).toBe(21);
  });

  it("ignores an unknown tag rather than throwing", () => {
    expect(() => net.dispatch(new Uint8Array([0xfe, 1, 2]).buffer)).not.toThrow();
    expect(store.state.hello).toBeNull();
  });

  it("ignores an empty message", () => {
    expect(() => net.dispatch(new ArrayBuffer(0))).not.toThrow();
  });
});

describe("history", () => {
  it("accumulates one sample per colony per stats frame", () => {
    const s = new Store();
    s.applyStats(10, [colony(0), colony(1)]);
    s.applyStats(20, [colony(0), colony(1)]);
    expect(s.state.history.get(0)!.tick).toEqual([10, 20]);
    expect(s.state.history.get(1)!.tick).toEqual([10, 20]);
  });

  it("tracks delivered_total, the curve that answers whether it evolves", () => {
    const s = new Store();
    s.applyStats(10, [colony(0, { deliveredTotal: 5 })]);
    s.applyStats(20, [colony(0, { deliveredTotal: 9 })]);
    expect(s.state.history.get(0)!.deliveredTotal).toEqual([5, 9]);
  });

  it("is bounded, so a long run does not grow without limit", () => {
    const s = new Store();
    for (let t = 0; t < HISTORY_LEN + 50; t++) s.applyStats(t, [colony(0)]);
    const h = s.state.history.get(0)!;
    expect(h.tick.length).toBe(HISTORY_LEN);
    // The oldest samples fell off the front, newest is last.
    expect(h.tick[h.tick.length - 1]).toBe(HISTORY_LEN + 49);
    expect(h.tick[0]).toBe(50);
  });

  it("is cleared when the world is rebuilt", () => {
    // A reset or load restarts the tick counter. Charting the old world's
    // samples against the new world's ticks would draw a line that lies.
    const s = new Store();
    s.applyHello(hello(500));
    s.applyStats(500, [colony(0)]);
    expect(s.state.history.get(0)!.tick.length).toBe(1);

    s.applyHello(hello(0));
    expect(s.state.history.size).toBe(0);
  });

  it("survives a hello that merely moves forward", () => {
    const s = new Store();
    s.applyHello(hello(100));
    s.applyStats(100, [colony(0)]);
    s.applyHello(hello(200)); // the periodic refresh, not a reset
    expect(s.state.history.get(0)!.tick.length).toBe(1);
  });
});

describe("selection", () => {
  it("drops a genome that belongs to a different ant", () => {
    // Detail streams at 4 fps; genome arrives once on selection. If the server
    // switched ants, drawing old weights against new activations would be a
    // plausible-looking lie.
    const s = new Store();
    const net = dispatcher(s);
    net.dispatch(load("genome.bin")); // id 42
    expect(s.state.genome?.id).toBe(42);

    net.dispatch(load("detail.bin")); // id 0
    expect(s.state.genome).toBeNull();
    expect(s.state.detail?.id).toBe(0);
  });

  it("keeps a genome that matches the selected ant", () => {
    const s = new Store();
    s.applyGenome({ kind: "genome", id: 7, params: new Float32Array(1128) });
    s.applyDetail({
      kind: "detail",
      id: 7,
      colony: 0,
      alive: true,
      x: 0,
      y: 0,
      heading: 0,
      energy: 0,
      maxEnergy: 1,
      size: 1,
      carrying: 0,
      foodDelivered: 0,
      foodHarvested: 0,
      age: 0,
      lineage: 0,
      traits: new Float32Array(8),
      inputs: new Float32Array(44),
      h1: new Float32Array(16),
      h2: new Float32Array(16),
      outputs: new Float32Array(8),
      name: "",
    });
    expect(s.state.genome?.id).toBe(7);
  });

  it("clearing removes both detail and genome", () => {
    const s = new Store();
    const net = dispatcher(s);
    net.dispatch(load("genome.bin"));
    net.dispatch(load("detail.bin"));
    s.clearSelection();
    expect(s.state.detail).toBeNull();
    expect(s.state.genome).toBeNull();
  });
});

describe("notification", () => {
  it("notifies subscribers on stats but not on every ant frame", () => {
    // Ant frames land 20x a second. Waking every DOM subscriber to re-render
    // text that often is waste; the renderer polls on rAF instead.
    const s = new Store();
    const net = dispatcher(s);
    const spy = vi.fn();
    s.subscribe(spy);

    net.dispatch(load("ants.bin"));
    expect(spy).not.toHaveBeenCalled();

    net.dispatch(load("stats.bin"));
    expect(spy).toHaveBeenCalledTimes(1);
  });

  it("unsubscribe stops the callbacks", () => {
    const s = new Store();
    const spy = vi.fn();
    const off = s.subscribe(spy);
    off();
    s.setConnected(true);
    expect(spy).not.toHaveBeenCalled();
  });
});

describe("playback state", () => {
  it("choosing a speed implies running", () => {
    const s = new Store();
    expect(s.state.paused).toBe(true);
    s.setSpeed(2);
    expect(s.state.paused).toBe(false);
    expect(s.state.speed).toBe(2);
  });

  it("layer toggles flip independently", () => {
    const s = new Store();
    expect(s.state.layers.alarm).toBe(false);
    s.toggleLayer("alarm");
    expect(s.state.layers.alarm).toBe(true);
    expect(s.state.layers.food).toBe(true);
  });
});

describe("colony selection", () => {
  it("selects and clears the in-world colony popover", () => {
    const s = new Store();
    expect(s.selectedColony()).toBe(null);
    s.selectColony(3);
    expect(s.selectedColony()).toBe(3);
    s.clearSelection();
    expect(s.selectedColony()).toBe(null);
  });

  it("clearSelection also dismisses the colony popover", () => {
    // Escape and empty-ground clicks call clearSelection; both should close the
    // popover, not just deselect the ant.
    const s = new Store();
    s.selectColony(1);
    s.clearSelection();
    expect(s.selectedColony()).toBe(null);
  });

  it("caches nest centroids from the terrain frame", () => {
    const s = new Store();
    const rgba = new Uint8Array(2 * 2 * 4);
    rgba[(1 * 2 + 1) * 4 + 2] = 0; // colony 0 owns texel (1,1)
    rgba[0 * 4 + 2] = 255; // others unowned
    rgba[1 * 4 + 2] = 255;
    rgba[2 * 4 + 2] = 255;
    s.applyTerrain({ kind: "terrain", w: 2, h: 2, factor: 4, rgba, tick: 5 } as never);
    expect(s.state.nestCentroids.get(0)).toEqual({ x: 6, y: 6 });
  });
});

describe("selection + tabs", () => {
  it("selecting an entity records it and switches to the explorer tab", () => {
    const s = new Store();
    s.selectTile(3, 4);
    expect(s.state.selection).toEqual({ kind: "tile", x: 3, y: 4 });
    expect(s.state.activeTab).toBe("explorer");
  });
  it("selectedColony() reflects a colony selection and nothing else", () => {
    const s = new Store();
    s.selectColony(2);
    expect(s.selectedColony()).toBe(2);
    s.selectTile(0, 0);
    expect(s.selectedColony()).toBeNull();
  });
  it("clearSelection wipes selection, detail, genome", () => {
    const s = new Store();
    s.selectAnt();
    s.clearSelection();
    expect(s.state.selection).toBeNull();
  });
  it("worldSummary sums pop, store, delivered", () => {
    const sum = worldSummary([
      { id: 0, population: 3, store: 10, deliveredTotal: 100 },
      { id: 1, population: 4, store: 5, deliveredTotal: 250 },
    ] as never);
    expect(sum).toEqual({ pop: 7, store: 15, delivered: 350 });
  });
});
